---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: services.app.pac.io
spec:
  group: app.pac.io
  names:
    kind: Service
    listKind: ServiceList
    plural: services
    singular: service
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Service is the Schema for the services API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ServiceSpec defines the desired state of Service
            properties:
              catalog:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
                x-kubernetes-map-type: atomic
                x-kubernetes-validations:
                - message: catalog is immutable
                  rule: self == oldSelf
              display_name:
                type: string
              expiry:
                format: date-time
                type: string
              ssh_keys:
                items:
                  type: string
                type: array
              user_id:
                type: string
                x-kubernetes-validations:
                - message: user_id is immutable
                  rule: self == oldSelf
            required:
            - catalog
            - display_name
            - expiry
            - ssh_keys
            - user_id
            type: object
          status:
            description: ServiceStatus defines the observed state of Service
            properties:
              accessInfo:
                type: string
              expired:
                type: boolean
              message:
                type: string
              state:
                description: ServiceState is state of catalog
                enum:
                - NEW
                - IN_PROGRESS
                - CREATED
                - FAILED
                - EXPIRED
                type: string
              vm:
                description: VM has the detail of provisioned vm service
                properties:
                  instance_id:
                    type: string
                  ip_address:
                    type: string
                  state:
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
